package com.bettertoppi.topuhud.modmenu;

import com.bettertoppi.topuhud.config.ConfigManager;
import com.bettertoppi.topuhud.config.TopuHudConfig;
import java.util.Locale;

public final class TopuUtilityManager {
    private TopuUtilityManager() {}
    public enum Category { COMBAT, HUD, MOVEMENT, VISUAL, WORLD, PERFORMANCE, MISC }
    public record Utility(String id,String name,String description,Category category,String configField) {}
    public static final Utility[] ALL={
        u("fps","FPS Counter","Live frames per second",Category.HUD,"fpsCounter"),u("ping","Ping","Network latency display",Category.HUD,"pingDisplay"),u("tps","TPS","Server tick-rate display",Category.HUD,"tpsDisplay"),u("cps","CPS Counter","Clicks per second",Category.COMBAT,"cpsDisplay"),u("combo","Combo Counter","Current hit combo",Category.COMBAT,"comboCounter"),
        u("armor","Armor HUD","Armor and durability display",Category.HUD,"armorHud"),u("effects","Status Effects","Active potion effects",Category.HUD,"potionEffects"),u("potions","Potion Counter","Potion inventory count",Category.HUD,"potionCounter"),u("gapples","Gapple Counter","Golden apple count",Category.COMBAT,"gappleCounter"),u("totems","Totem Counter","Totem inventory count",Category.COMBAT,"totemCounter"),
        u("enemyhp","Enemy HP","Target health display",Category.COMBAT,"enemyHealth"),u("cooldown","Attack Cooldown","Attack recharge display",Category.COMBAT,"cooldown"),u("warning","Armor Warning","Low durability warning",Category.COMBAT,"armorWarning"),u("blockoverlay","Block Overlay","Looking-at block information",Category.WORLD,"blockOverlay"),u("keystrokes","Keystrokes","Movement and mouse keys",Category.HUD,"keystrokes"),
        u("memory","Memory","JVM memory usage",Category.PERFORMANCE,"memory"),u("autosprint","Auto Sprint","Automatically sprint forward",Category.MOVEMENT,"autoSprint"),u("togglesneak","Toggle Sneak","Toggle sneak with a key",Category.MOVEMENT,"toggleSneak"),u("coordinates","Coordinates","Compact XYZ coordinates",Category.HUD,"utilityCoordinates"),u("direction","Direction","Facing direction display",Category.HUD,"utilityDirection"),
        u("speed","Speed","Current movement speed",Category.MOVEMENT,"utilitySpeed"),u("jumpcount","Jump Counter","Count jumps while playing",Category.MOVEMENT,"utilityJumpCounter"),u("fall","Fall Distance","Current fall distance",Category.MOVEMENT,"utilityFallDistance"),u("sprintstatus","Sprint Status","Current sprint state",Category.MOVEMENT,"utilitySprintStatus"),u("velocity","Velocity","Horizontal movement velocity",Category.MOVEMENT,"utilityVelocity"),
        u("crosshair","Custom Crosshair","Client crosshair overlay",Category.VISUAL,"utilityCrosshair"),u("hitcolor","Hit Color","Visual hit feedback",Category.COMBAT,"utilityHitColor"),u("hitsound","Hit Sound","Combat hit feedback",Category.COMBAT,"utilityHitSound"),u("reach","Reach Display","Target distance display",Category.COMBAT,"utilityReach"),u("attackindicator","Attack Indicator","Attack readiness indicator",Category.COMBAT,"utilityAttackIndicator"),
        u("zoom","Zoom","Camera zoom utility",Category.VISUAL,"utilityZoom"),u("fullbright","Fullbright","Maximum client brightness",Category.VISUAL,"utilityFullbright"),u("fpslimit","FPS Limiter","Client frame-rate control",Category.PERFORMANCE,"utilityFpsLimiter"),u("lowlatency","Low Latency","Reduced visual overhead mode",Category.PERFORMANCE,"utilityLowLatency"),u("cleanhud","Clean HUD","Minimal HUD mode",Category.VISUAL,"utilityCleanHud"),
        u("minimalparticles","Minimal Particles","Reduce particle clutter",Category.PERFORMANCE,"utilityMinimalParticles"),u("itemphysics","Item Physics","Enhanced dropped-item presentation",Category.VISUAL,"utilityItemPhysics"),u("clock","Clock","Real-world time display",Category.HUD,"utilityClock"),u("server","Server","Current server display",Category.HUD,"utilityServer"),u("biome","Biome","Current biome display",Category.WORLD,"utilityBiome"),
        u("facing","Facing","Precise cardinal facing",Category.WORLD,"utilityFacing"),u("chunk","Chunk Info","Current chunk coordinates",Category.WORLD,"utilityChunkInfo"),u("light","Light Level","Block light information",Category.WORLD,"utilityLightLevel"),u("target","Target Info","Crosshair target details",Category.COMBAT,"utilityTargetInfo"),u("durability","Durability","Held-item durability display",Category.HUD,"utilityDurability"),
        u("helditem","Held Item","Held item information",Category.HUD,"utilityHeldItem"),u("gamemode","Game Mode","Current game mode display",Category.WORLD,"utilityGamemode"),u("difficulty","Difficulty","Current world difficulty",Category.WORLD,"utilityDifficulty"),u("fpsgraph","FPS Graph","Recent FPS history graph",Category.PERFORMANCE,"utilityFpsGraph"),u("session","Session","Session play-time display",Category.MISC,"utilitySession")};
    private static Utility u(String id,String name,String description,Category category,String field){return new Utility(id,name,description,category,field);}
    public static boolean isEnabled(Utility u){try{return TopuHudConfig.class.getField(u.configField()).getBoolean(ConfigManager.get());}catch(Exception e){return false;}}
    public static void setEnabled(Utility u,boolean enabled){try{TopuHudConfig.class.getField(u.configField()).setBoolean(ConfigManager.get(),enabled);}catch(Exception ignored){}}
    public static Utility[] search(String query,Category category){String q=query==null?"":query.trim().toLowerCase(Locale.ROOT);return java.util.Arrays.stream(ALL).filter(u->category==null||u.category()==category).filter(u->q.isEmpty()||u.name().toLowerCase(Locale.ROOT).contains(q)||u.description().toLowerCase(Locale.ROOT).contains(q)).toArray(Utility[]::new);}
}
