pluginManagement {
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.terraformersmc.com/releases/" }
        mavenCentral()
    }
}
rootProject.name="TopuHUD-1.21.5"
